version: "3.8"

volumes:
  controller_data:

services:
  webots:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROJECT_PATH=/usr/local/webots-project
        - WORLD_PATH=webots-project/worlds/pit_escape.wbt
    command: webots --batch --stdout --stderr webots-project/worlds/pit_escape.wbt
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=$XAUTHORITY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - '3005:1234'
    privileged: true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ${XAUTHORITY:-/dev/null}:${XAUTHORITY:-/dev/null}
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- controller_data:/usr/local/webots-project:rw

  controller:
    depends_on:
      - webots
    restart: 'unless-stopped'
    build:
      context: .
      dockerfile: controller_Dockerfile
      args:
        - DEFAULT_CONTROLLER=pit_escape
        - PORT=3005
        - PROJECT_PATH=/usr/local/webots-project
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
    tty: true # docker run -t
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WEBOTS_STDOUT_REDIRECT=1
      - WEBOTS_STDERR_REDIRECT=1

#  theia:
#    image: benjamindeleze/theia-test:test3
#    ports:
#      - $THEIA_PORT:3000
#    volumes:
#      - controller_data:/home/project/webots-project:rw
